language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - pip install codecov
  - pip install 'coverage<4'
script:
  - coverage run -a src/bencode.py
  - coverage run -a src/crc32c.py
  - coverage run -a src/krpc.py
  - coverage run -a src/dht.py
  - coverage run -a src/tracker.py
after_success:
  - codecov
